apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ftlzbequn-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ftlzbequn-java-springboot-gitops